stateDiagram-v2
    [*] --> Idle

    Idle --> Monitoring : start application\nApplication.main()
    Monitoring : operator.monitor()

    Monitoring --> Evaluating : new Measure(150.0)\necologist.checkExcess(measure)

    state Evaluating {
        [*] --> ThresholdCheck
        ThresholdCheck --> ThresholdExceeded : measure.value > 100
        ThresholdCheck --> ThresholdOk : else

        ThresholdExceeded --> [*]
        ThresholdOk --> [*]
    }

    Evaluating --> Alerting : якщо ThresholdExceeded\nnew Event(...)\ndispatcher.receiveAlert(event)
    Evaluating --> Planning : якщо ThresholdOk\n(без тривоги)

    Alerting : dispatcher.receiveAlert(event)

    Alerting --> Planning : завершення оповіщення
    Planning : ecologist.planService()

    Planning --> Reporting : operator.report()
    Reporting : формування звіту

    Reporting --> Completed : завершення сценарію
    Completed --> [*]
